apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: geteway
  template:
    metadata:
      labels:
        app: geteway
    spec:
      containers:
        - name: gateway
          image: wupoyi/skypay-gateway:latest
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: ‘6379’
            - name: POSTGRES_HOST
              value: postgres-cluster-ip-service
            - name: POSTGRES_PORT
              value: ‘5432’
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: skypay-secret
                  key: POSTGRES_PASSWORD
